apolloconfig/agollo

app_config.go, app_config_server_test.go, componet_notify.go, componet_timer.go, config_server_test.go, json_config_test.go, log.go, notify_server_test.go, repository.go, request.go, request_server_test.go, start.go
由于公司内部使用的是自定义log实现，希望可以在Start时传入logger替换默认的seelog.
如果仍然需要使用seelog，可以调用原先的Start()
=> feat: replace with custom log

repository.go
之前由于在事件通知前做了保护，导致当key删完之后，不会发送事件通知.
=> fix: 将key全部删除时，仍应该发送事件通知

CONTRIBUTING.md, go.mod, parser.go, repository.go, start.go
=> Fix version semantic errors #83

agcache/cache.go, agcache/memory/memory.go, agcache/memory/memory_test.go, component/notify/change_event_test.go, component/notify/componet_notify.go, env/apollo_config.go, env/file/json/json_test.go, env/file/json/raw.go, env/file/json/raw_test.go, extension/cache_test.go, extension/format_parser_test.go, repository.go, repository_test.go, start.go, start_test.go, storage/change_event.go, storage/event_dispatch.go, storage/event_dispatch_test.go, storage/repository.go, storage/repository_test.go, utils/parse/normal/parser.go, utils/parse/parser.go, utils/parse/properties/parser.go, utils/parse/yaml/parser.go, utils/parse/yaml/parser_test.go, utils/parse/yml/parser_test.go
1. 增加yaml后缀的格式解析，对接apollo的类型
2. 实现list类型配置的解析写入和读取
3. 修改了OnChange事件保存的value类型为interface
4. 提供为某些key注册Listener，从而实现对某些key进行事件处理；注册支持模糊匹配
=> 增加数组的写入和读取，完成单独key的事件处理

README.md, client.go
你好，当我使用 extension.AddFormatParser(constant.YAML, &configParser{})时，发现 agollo.create 中会覆盖掉 yaml的解析。
=> extension相关初始化提到 init 中处理

protocol/http/request.go
=> fix http response memory leak

component/remote/sync.go
* 当同步获取配置失败时增加读取本地配置文件  fix #148
=> [Fix]: 当同步获取配置失败时增加读取本地配置文件 

client.go, client_test.go, cluster/load_balance.go, cluster/roundrobin/round_robin.go, cluster/roundrobin/round_robin_test.go, component/common_test.go, component/notify/change_event_test.go, component/notify/componet_notify.go, component/remote/abs.go, component/remote/async.go, component/remote/async_test.go, component/remote/remote.go, component/remote/sync.go, component/remote/sync_test.go, component/serverlist/sync.go, component/serverlist/sync_test.go, env/app_config_test.go, env/config/config.go, env/config/config_test.go, env/server/server.go, env/server/server_test.go, extension/load_balance_test.go, protocol/http/request.go, protocol/http/request_test.go, start_test.go, storage/repository.go, storage/repository_test.go
=> [Fix]：修复 data race 的问题

storage/change_event.go, storage/change_event_test.go, storage/repository.go
=> Add update time for change event

README.md, component/remote/async.go, component/remote/async_test.go, env/config/config.go, env/config/config_test.go
修复#164问题 
1.修改Sync方法，只拉取发生改变的namspace
2.只有拉取改变的namespace成功后，才更新notify id
=> 修改当更新配置失败时会导致后续再也无法更新的问题

protocol/http/request.go, protocol/http/request_test.go
1. 复用Transport避免goroutine泄露
2. 运行时才设置InsecureSkipVerify逃脱CodeQL静态检查
3. 将TestHttpsRequestRecovery前置规避测试失败
=> fix: 复用Transport避免goroutine泄露

component/log/log.go, protocol/http/request.go
=> [Fix]: 修复一些 log 相关的问题

client.go, client_test.go, storage/repository.go, storage/repository_test.go
* Fixed #215 修复当调用  repository.go 中 GetXXXValue，类型不一致时的报错
* 聚合 `client.go` 的 `GetXXXValue` 方法到 `repository.go`
=> [Fix] 修复当调用  repository.go 中 GetXXXValue，类型不一致时的报错

protocol/http/request.go
我把控制台打印日志贴出来供参考：
==================
WARNING: DATA RACE
Read at 0x000006033768 by goroutine 7:
github.com/apolloconfig/agollo/v4/protocol/http.getDefaultTransport()
/Users/wubin1989/go/pkg/mod/github.com/apolloconfig/agollo/v4@v4.1.0/protocol/http/request.go:63 +0x31
github.com/apolloconfig/agollo/v4/protocol/http.Request()
/Users/wubin1989/go/pkg/mod/github.com/apolloconfig/agollo/v4@v4.1.0/protocol/http/request.go:111 +0x1e4
github.com/apolloconfig/agollo/v4/component/serverlist.SyncServerIPList()
/Users/wubin1989/go/pkg/mod/github.com/apolloconfig/agollo/v4@v4.1.0/component/serverlist/sync.go:90 +0x29c
github.com/apolloconfig/agollo/v4/component/serverlist.(*SyncServerIPListComponent).Start()
/Users/wubin1989/go/pkg/mod/github.com/apolloconfig/agollo/v4@v4.1.0/component/serverlist/sync.g …
=> fix data race from getDefaultTransport 这个api会产生data race

protocol/http/request.go
在使用 VPN 代理时，没有跟随环境代理，并且源码中的跳过 SSL 失效，会抛出以下异常，我修改了跟随系统 Proxy 与 SSL 跳过的源码来修复这个问题
```
Connect Apollo Server Fail,url:%s,Error:%s [https://****.com/services/config?appId=****&ip=192.168.2.102 Get "https://****.com/services/config?appId=****&ip=192.168.2.102": context deadline exceeded (Client.Timeout exceeded while awaiting headers)]
```
=> fix: 不跟随系统vpn代理

env/file/json/json.go
使用os.MkdirAll instead of os.Mkdir
=> To prevent backup failed using MkDirAll instead of Mkdir

component/remote/abs.go
请求路径是这样的：SyncWithNamespace -> RequestRecovery -> Request -> 响应中的code为http.StatusNotModified（return nil, nil），SyncWithNamespace函数后续会判断返回的*config.ApolloConfig是否为nil，显然这时为nil的，那么会输出warning日志(apolloConfig is nil)。
由于该处理逻辑会定时触发，这样会导致业务代码频繁输出日志（apolloConfig is nil）。
请求修正
=> Using debug logging when 304 http code returned from server

component/common_test.go, component/remote/async.go, component/remote/sync.go, component/serverlist/sync.go, env/config/json/json_config.go, env/file/json/json.go, protocol/http/request.go, protocol/http/request_test.go, storage/repository.go
=> chore: using log with format method

client.go, component/notify/componet_notify.go
Developers normally write code to dynamicly create clients. Every client will poll to fetch latest configuration. So there will be more and more clients and connections which are unnecessary.
=> 添加 Close() 方法停止轮询

env/server/server.go, protocol/http/request.go
fix https://github.com/apolloconfig/agollo/issues/260
=> [FIX] fix: sdk load balance

client.go, storage/repository.go, storage/repository_test.go
Fix #264 
本次只是修复可以通过以下形式读取配置：
```
a=a,b,d,c
```
后续需要切换底层数据源进行支持。
=> [Fix]修复不能通过 string 和 int 格式化数组

client.go
=> [Fix]删除无用方法

component/remote/abs.go
=> fix: enable retry for the SyncWithNamespace

env/server/server.go, extension/file_test.go, storage/event_dispatch.go, storage/repository.go
1. [env/server/server.go] strings.Contains instead of strings.Index
2. [extension/file_test.go] type assertion to the same type
3. [storage/event_dispatch.go] simplifying error checking
4. [storage/repository.go] when checking the length of map[string]interface{}, the nil check can be ignored
5. code comment formatting
=> refactor: code optimisation

component/remote/async_test.go, protocol/http/request.go, protocol/http/request_server_test.go, protocol/http/request_test.go
#296 
- Failfast http status code: 400, 401, 404, 405
- Error Code Description: https://www.apolloconfig.com/#/en/usage/other-language-client-user-guide?id=_16-error-code-description
=> Failfast for explicit error http request instead of retrying (#296)

component/remote/abs.go, component/serverlist/sync.go
见 https://pkg.go.dev/time#pkg-constants
```
To convert an integer number of units to a Duration, multiply:
seconds := 10
fmt.Print(time.Duration(seconds)*time.Second) // prints 10s
```
=> refactor: simplify the conversion from int to time.Duration as suggested by the golang offical doc.

protocol/auth/sign/sign.go, protocol/auth/sign/sign_test.go
In case apollo server using sha256 hash function as signature, the signature function can support also.
=> Make hash function in signature settable
