README.md
request.go

change info level instead while config is not modifie

Qianjie fix

---

repository.go

当key的value没有变化时，不应该推送这个key的事件通知

fix: 当key的value没有变化时，不推送这个key的事件通知

---

repository.go
repository_test.go

fix data race bug in https://github.com/zouyx/agollo/issues/26
by the way, I suggest you fmt your code by `go fmt ./...`

fix data race

---

start.go

您好，我在用此项目时，将log改成自定义的，但是启动时log的输出格式还是seelog的，开了下源码，这里是写死的，希望您能斟酌一下

change seelog to custom logger

---

go.mod
go.sum
repository.go
request.go

[Feature]增加go module和一些错误log

---

change_event.go
change_event_test.go
start_test.go

[Enhancement]修改使用actionlistener方式

---

.travis.yml
depend.sh

[Enhancement]更新travis

---

app_config.go
app_config_test.go
request_test.go

* 修改servers的Map为sync.map,Ref #44

[Bug]修改servers的Map为sync.map

---

.dependabot/config.yml
.github/auto-comment.yml
.github/stale.yml
agcache/cache.go
agcache/default.go
componet_notify_test.go
go.mod
go.sum
repository.go
repository_test.go

* 去除FreeCache，切换成sync.map
* 修复定时更新问题 #62

[Bug]去除FreeCache

---

.github/auto-comment.yml
.gitignore
app_config.go
json_config_test.go

[Feature]增加根据环境变量读取配置文件地址

---

app_config.go
componet_notify.go
parser.go
repository.go
start.go

* 增加json.properties,yml解析
* 整理agollo初始化顺序

[Feature]增加文件解析

---

app_config.go
componet_notify.go
componet_notify_test.go
repository.go

* 运行时获取namespace，只是运行时动态获取及异步更新 #73

[Feature]增加运行时获取namespace

---

file.go

[Bug]修复第一次写备份文件失败

---

app_config.go
app_config_test.go
componet_notify.go
go.sum
start.go

* 修复使用不存在的namespace后，启动停滞 60s 后才运行 Ref#40

[Bug]修复使用不存在的namespace后，启动停滞 60s 后才运行

---

component/notify/componet_notify.go
component/notify/componet_notify_test.go
env/app_config.go
env/app_config_test.go
loadbalance/load_balance_test.go

Fix: concurrent problems

---

component/notify/componet_notify.go
component/serverlist/sync.go
env/app_config.go
start.go

fix: 其他组件的初始化应该在配置初始化之后

---

mock_server_test.go
protocol/http/request.go
protocol/http/request_test.go
start.go
start_test.go

1.fix test case
2.optimizate http package

Fix: optimizate http package

---

component/log/log.go

删除LoggerInterfac接口中方法的返回值

---

component/notify/componet_notify.go
component/serverlist/sync.go
env/config/config.go
env/request_config.go
extension/sgin_test.go
extension/sign.go
protocol/auth/auth.go
protocol/auth/sign/sign.go
protocol/auth/sign/sign_test.go
protocol/http/request.go
start.go
start_test.go

[Feature]:增加客户端鉴权

---

protocol/http/request.go
protocol/http/request_server_test.go
protocol/http/request_test.go

支持https并且跳过身份认

---

start.go

Fix: 修复变更时间问题

---

storage/repository.go

*  修复 change event 问题 Fix #124 #125

[Fix]: 修复 change event 问题

---

component/notify/change_event_test.go
storage/change_event.go
storage/change_event_test.go
storage/event_dispatch.go
storage/repository.go

[FEATURE]: 调整 listener 顺序

---

protocol/http/request.go

将Apollo配置无更新时的提示信息降级为debug
#135

将Apollo配置无更新时的提示信息降级为debug

---

component/serverlist/sync.go
component/serverlist/sync_test.go
env/config/config.go

[FEATURE]: 增加同步服务器列表自定义超时时间

---

client.go
client_test.go
component/notify/componet_notify.go
storage/repository.go
storage/repository_test.go

[Fix]:去除无用标识位

---

README.md

doc: 修复 readme 中错误的 demo

---

.github/FUNDING.yml
component/remote/abs.go

SyncWithNamespace 支持自定义超时时间

---

.github/FUNDING.yml
client.go
client_test.go
start_test.go

feat(client):Change Client from struct to interface

---

protocol/http/request.go

fix err fmt

---

env/file/json/json.go
env/file/json/json_test.go
env/file/json/raw_test.go

[Fix] 创建备份文件时写标志错误
